spring:
  application:
    name: arfi-auth-service
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: ${GOOGLE_CLIENT_ID}
            clientSecret: ${GOOGLE_CLIENT_SECRET}
            scope: profile, email

  datasource:
    url: jdbc:postgresql://localhost:5432/arfi_auth
    username: arfi_user
    password: password123
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  docker:
    compose:
      enabled: false

#springdoc:
#  api-docs:
#    path: /api-docs
#  swagger-ui:
#    path: /swagger-ui.html

# ... existing config ...

server:
  port: ${SERVER_PORT:8080}

jwt:
  secret: 306F635266556A586E3272357538782F413F4428472B4B6250645367566F8890
  # 5 Minutes for Access Token
  access-expiration: 300000
  # 7 Days for Refresh Token
  refresh-expiration: 604800000

frontend:
  url: ${FRONTEND_URL:http://localhost:5173}