spring:
  application:
    name: arfi-auth-service

  datasource:
    url: jdbc:postgresql://localhost:5432/arfi_auth
    username: arfi_user
    password: password123
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  docker:
    compose:
      enabled: false

#springdoc:
#  api-docs:
#    path: /api-docs
#  swagger-ui:
#    path: /swagger-ui.html

# ... existing config ...

jwt:
  secret: 306F635266556A586E3272357538782F413F4428472B4B6250645367566F8890
  # 15 Minutes for Access Token
  access-expiration: 900000
  # 7 Days for Refresh Token
  refresh-expiration: 604800000